In [45]:
from tensorflow.keras.preprocessing.text import one_hot

In [46]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [47]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [48]:
## Define the vocabulary size
voc_size=10000

In [49]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [50]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[6690, 5461, 4227, 2426],
 [6690, 5461, 4227, 231],
 [6690, 9363, 4227, 7385],
 [7556, 3743, 857, 2566, 7027],
 [7556, 3743, 857, 2566, 1281],
 [3017, 6690, 8028, 4227, 1601],
 [6690, 7582, 6802, 2566]]

In [51]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences  # earlier lies 

from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [52]:
import numpy as np

In [53]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6690 5461 4227 2426]
 [   0    0    0    0 6690 5461 4227  231]
 [   0    0    0    0 6690 9363 4227 7385]
 [   0    0    0 7556 3743  857 2566 7027]
 [   0    0    0 7556 3743  857 2566 1281]
 [   0    0    0 3017 6690 8028 4227 1601]
 [   0    0    0    0 6690 7582 6802 2566]]


In [54]:
## feature representation
dim=10

In [55]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [56]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_4 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:
model.predict(embedded_docs)  ## vectors of all words in sentences

1/1 [==============================] - 0s 42ms/step


array([[[-0.01986088, -0.04027405, -0.02947913, -0.01404029,
         -0.00227326,  0.03149107, -0.0370028 ,  0.00474364,
          0.02835962,  0.02127862],
        [-0.01986088, -0.04027405, -0.02947913, -0.01404029,
         -0.00227326,  0.03149107, -0.0370028 ,  0.00474364,
          0.02835962,  0.02127862],
        [-0.01986088, -0.04027405, -0.02947913, -0.01404029,
         -0.00227326,  0.03149107, -0.0370028 ,  0.00474364,
          0.02835962,  0.02127862],
        [-0.01986088, -0.04027405, -0.02947913, -0.01404029,
         -0.00227326,  0.03149107, -0.0370028 ,  0.00474364,
          0.02835962,  0.02127862],
        [-0.01265617, -0.01954744,  0.0075193 , -0.01336397,
          0.02931913,  0.00318199,  0.03474566, -0.01990941,
         -0.00592214, -0.02952826],
        [ 0.03677548,  0.01686294, -0.00876013,  0.0436161 ,
          0.02301362, -0.03241082,  0.04584063, -0.01700328,
          0.01506538,  0.04006686],
        [-0.00818066,  0.0492194 ,  0.01307603,  0.0

In [58]:
embedded_docs[0]

array([   0,    0,    0,    0, 6690, 5461, 4227, 2426])

In [60]:
model.predict(embedded_docs[0])  # vectors of each word in first sentence ,each word represented in 10 dimensions

1/1 [==============================] - 0s 15ms/step


array([[-0.01986088, -0.04027405, -0.02947913, -0.01404029, -0.00227326,
         0.03149107, -0.0370028 ,  0.00474364,  0.02835962,  0.02127862],
       [-0.01986088, -0.04027405, -0.02947913, -0.01404029, -0.00227326,
         0.03149107, -0.0370028 ,  0.00474364,  0.02835962,  0.02127862],
       [-0.01986088, -0.04027405, -0.02947913, -0.01404029, -0.00227326,
         0.03149107, -0.0370028 ,  0.00474364,  0.02835962,  0.02127862],
       [-0.01986088, -0.04027405, -0.02947913, -0.01404029, -0.00227326,
         0.03149107, -0.0370028 ,  0.00474364,  0.02835962,  0.02127862],
       [-0.01265617, -0.01954744,  0.0075193 , -0.01336397,  0.02931913,
         0.00318199,  0.03474566, -0.01990941, -0.00592214, -0.02952826],
       [ 0.03677548,  0.01686294, -0.00876013,  0.0436161 ,  0.02301362,
        -0.03241082,  0.04584063, -0.01700328,  0.01506538,  0.04006686],
       [-0.00818066,  0.0492194 ,  0.01307603,  0.04345934, -0.0105437 ,
        -0.01579915,  0.01103332,  0.00780051